version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-bank_account}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - /bank-account/docker:/var/lib/postgresql/data

volumes:
  db-data:

